# pull official base image
FROM node:alpine

# set working directory
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# install app dependencies
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

ENV REACT_APP_DICTIONARY_API=https://api.dictionaryapi.dev/api/v2/entries
ENV REACT_APP_WORDTRACKER_API=http://192.168.1.76:3005

# start app
CMD ["npm", "start"]