FROM node:alpine as build
WORKDIR /app
COPY package.json .
RUN npm install
ARG REACT_APP_DICTIONARY_API
ARG REACT_APP_WORDTRACKER_API
COPY . ./
RUN npm run build

# production environment
FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
# COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

ARG NGINX_WORD_TRACKER_API
ARG NGINX_DICTIONARY_API
ARG NGINX_PORT
COPY nginx/templates /etc/nginx/templates

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]